version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/decidim.tar
            - /caches/decidim-dev.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/decidim.tar | true
            docker load -i /caches/decidim-dev.tar | true
      - run:
          name: Build docker images
          command: |
            export DECIDIM_VERSION=`cat decidim-version.txt`

            docker build -f Dockerfile \
                         --build-arg decidim_version=$DECIDIM_VERSION \
                         -t decidim/decidim:$CIRCLE_SHA1 \
                         -t decidim/decidim:$DECIDIM_VERSION \
                         -t decidim/decidim:latest \
                         --cache-from=decidim/decidim:latest .

            docker build -f Dockerfile-dev \
                         --build-arg decidim_version=$DECIDIM_VERSION \
                         -t decidim/decidim:$CIRCLE_SHA1-dev \
                         -t decidim/decidim:$DECIDIM_VERSION-dev \
                         -t decidim/decidim:latest-dev \
                         --cache-from=decidim/decidim:latest-dev .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/decidim.tar decidim/decidim:latest
            docker save -o /caches/decidim-dev.tar decidim/decidim:latest-dev
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/decidim.tar
            - /caches/decidim-dev.tar
      - deploy:
          name: Push application Docker image
          command: |
            export DECIDIM_VERSION=`cat decidim-version.txt`

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push decidim/decidim:$DECIDIM_VERSION
              docker push decidim/decidim:$CIRCLE_SHA1
              docker push decidim/decidim:latest
              docker push decidim/decidim:$DECIDIM_VERSION-dev
              docker push decidim/decidim:$CIRCLE_SHA1-dev
              docker push decidim/decidim:latest-dev
            fi
