on:
  workflow_call:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      GENERATOR_IMAGE_NAME: decidim/decidim-generator
      TEST_IMAGE_NAME: decidim/decidim-test
      DEV_IMAGE_NAME: decidim/decidim-dev
      APP_IMAGE_NAME: decidim/decidim
      TAG: ${{ github.sha }}
    steps:
      - name: Fetch Decidim Tag
        id: decidim-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: decidim/decidim
          releases-only: true

      - name: Set Ruby Version
        id: ruby-version
        env:
          RUBY_VERSION_URL: https://raw.githubusercontent.com/decidim/decidim/${{ steps.decidim-tag.outputs.tag }}/.ruby-version
        run: |
          echo ::set-output name=version::$(curl -s $RUBY_VERSION_URL)
      - name: Set Decidim Version
        id: decidim-version
        run: echo ::set-output name=version::$(echo ${{ steps.decidim-tag.outputs.tag }} | cut -c2-)

      - name: Checkout Our Repo
        uses: actions/checkout@v2

      - name: Build decidim-generator Image
        env:
          RUBY_VERSION: ${{ steps.ruby-version.outputs.version }}
          DECIDIM_VERSION: ${{ steps.decidim-version.outputs.version }}
        run: |
          docker build \
          --build-arg ruby_version=$RUBY_VERSION \
          --build-arg decidim_version=$DECIDIM_VERSION \
          --file Dockerfile-generator \
          -t $GENERATOR_IMAGE_NAME .
          docker tag $GENERATOR_IMAGE_NAME $GENERATOR_IMAGE_NAME:$TAG
          docker tag $GENERATOR_IMAGE_NAME ghcr.io/$GENERATOR_IMAGE_NAME:$TAG
          docker tag $GENERATOR_IMAGE_NAME $GENERATOR_IMAGE_NAME:$DECIDIM_VERSION
          docker tag $GENERATOR_IMAGE_NAME ghcr.io/$GENERATOR_IMAGE_NAME:$DECIDIM_VERSION
      -
        name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: decidim/decidim-generator
          dockerfile: ./Dockerfile-generator
          severity_threshold: HIGH
          annotations: true
      -
        name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}