name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'Dockerfile'
    - '.github/workflows/on_push.yml'

jobs:
  build-publish:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    env:
      GENERATOR_IMAGE_NAME: ghcr.io/${{ github.actor }}/decidim-generator
      APP_IMAGE_NAME: ghcr.io/${{ github.actor }}/decidim
      TAG: ${{ github.sha }}

    steps:
    - name: Fetch Decidim Tag
      id: decidim-tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: decidim/decidim
        releases-only: true

    - name: Set Ruby Version
      id: ruby-version
      env:
        RUBY_VERSION_URL: https://raw.githubusercontent.com/decidim/decidim/${{ steps.decidim-tag.outputs.tag }}/.ruby-version
      run: |
        echo ::set-output name=version::$(curl -s $RUBY_VERSION_URL)

    - name: Set Decidim Version
      id: decidim-version
      run: echo ::set-output name=version::$(echo ${{ steps.decidim-tag.outputs.tag }} | cut -c2-)
      
    - name: Checkout Our Repo
      uses: actions/checkout@v2

    - name: Build decidim-generator Image
      env:
        RUBY_VERSION: ${{ steps.ruby-version.outputs.version }}
        DECIDIM_VERSION: ${{ steps.decidim-version.outputs.version }}
      run: |
        docker build \
        --build-arg ruby_version=$RUBY_VERSION \
        --build-arg decidim_version=$DECIDIM_VERSION \
        -t $GENERATOR_IMAGE_NAME:$TAG .
        docker tag $GENERATOR_IMAGE_NAME:$TAG $GENERATOR_IMAGE_NAME:latest
        docker tag $GENERATOR_IMAGE_NAME:$TAG $GENERATOR_IMAGE_NAME:$DECIDIM_VERSION

    - name: Publish Image to Github Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
    - run: |
        docker push $GENERATOR_IMAGE_NAME

    - name: Build decidim (app) Image
      env:
        RUBY_VERSION: ${{ steps.ruby-version.outputs.version }}
        DECIDIM_VERSION: ${{ steps.decidim-version.outputs.version }}
      run: |
        docker build \
        --file Dockerfile-deploy \
        --build-arg base_image=$GENERATOR_IMAGE_NAME \
        -t $APP_IMAGE_NAME:$TAG .
        docker tag $APP_IMAGE_NAME:$TAG $APP_IMAGE_NAME:latest
        docker tag $APP_IMAGE_NAME:$TAG $APP_IMAGE_NAME:$DECIDIM_VERSION

    - name: Publish Image to Github Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
    - run: |
        docker push $APP_IMAGE_NAME
